# -*- coding: utf-8 -*-
"""SentimentAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q04l_jfjVj2ErQBQ_NcEI6XdvNSCkbBK
"""

# some necessary imports
import os
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import seaborn as sns
from matplotlib import pyplot as plt

train_df = pd.read_csv('https://raw.githubusercontent.com/Fahim29/Project_SentimentAnalysis/master/Project/train-balanced-sentiment.csv',dtype=object)

train_df.head()

train_df.info()

train_df['sentiment'].value_counts()

train_df.dropna(subset=['review'], inplace=True)

train_texts, valid_texts, y_train, y_valid = train_test_split(train_df['review'], train_df['sentiment'], random_state=17)

# build bigrams, put a limit on maximal number of features
# and minimal word frequency
tf_idf = TfidfVectorizer(ngram_range=(1, 2), max_features=50000, min_df=2)
# multinomial  classifier
classifierNB = MultinomialNB()
# sklearn's pipeline
tfidf_NB_pipeline = Pipeline([('tf_idf', tf_idf), 
                                 ('classifierNB', classifierNB)])

# Commented out IPython magic to ensure Python compatibility.
# %%time
# tfidf_NB_pipeline.fit(train_texts, y_train)

valid_pred = tfidf_NB_pipeline.predict(valid_texts)

accuracy_score(y_valid, valid_pred)